name: Rchan CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GCC 13 and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-13 g++-13 cmake build-essential nlohmann-json3-dev

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      working-directory: ./build
      env:
        CC: gcc-13
        CXX: g++-13
      run: cmake ..

    - name: Build
      working-directory: ./build
      run: make

    - name: Run Rchan tests
      working-directory: ./build
      run: make testRchan

    - name: Run Speed tests
      working-directory: ./build
      run: make testSpeed